[deploy]
bucket = 'cfn-cruddur-artifacts'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:576997243977:certificate/04b1e86d-b723-4380-956e-2a5da1bbfe4e'
NetworkingStack = 'CrdNet'